const recipeTagLabelsDe = {
  'quick': 'Schnell',
  'savory': 'Herzhaft',
  'dessert': 'Dessert',
  'sweet': 'Süß',
  'breakfast': 'Frühstück',
  'lunch': 'Mittagessen',
  'dinner': 'Abendessen',
  'main': 'Hauptgericht',
  'side': 'Beilage',
  'dip': 'Dip',
  'sauce': 'Sauce',
  'bread': 'Brot',
  'snack': 'Snack',
  'vegetarian': 'Vegetarisch',
  'vegan': 'Vegan',
  'meat': 'Fleisch',
  'fish': 'Fisch',
  'one_pot': 'One pot',
  'rice': 'Reis',
  'pasta': 'Pasta',
  'soup': 'Suppe',
  'salad': 'Salat',
  'baking': 'Backen',
  'middle_eastern': 'Nahost',
  'saffron': 'Safran',
  'vegetables': 'Gemüse',
  'needs_review': 'Noch prüfen',
};

const selectableRecipeTagLabelsDe = {
  'quick': 'Schnell',
  'savory': 'Herzhaft',
  'dessert': 'Dessert',
  'sweet': 'Süß',
  'breakfast': 'Frühstück',
  'lunch': 'Mittagessen',
  'dinner': 'Abendessen',
  'main': 'Hauptgericht',
  'side': 'Beilage',
  'dip': 'Dip',
  'sauce': 'Sauce',
  'bread': 'Brot',
  'snack': 'Snack',
  'vegetarian': 'Vegetarisch',
  'vegan': 'Vegan',
  'meat': 'Fleisch',
  'fish': 'Fisch',
  'one_pot': 'One pot',
  'rice': 'Reis',
  'pasta': 'Pasta',
  'soup': 'Suppe',
  'salad': 'Salat',
  'baking': 'Backen',
};

String tagLabelDe(String key) {
  return recipeTagLabelsDe[key] ?? key;
}
